dist: trusty

sudo: required

services:
  - docker

language: go

go:
  - 1.5
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade

script:
  ./.travis/build.sh

after_success:
  ./.travis/push.sh
